version: 1
resources:
  - name: setup-telebot
    type: compute
    properties:
      instance_type: small
      os_image: ubuntu-20.04
      bootstrap_script: |
        #!/bin/bash
        set -e

        # Update package list and install Python3 and pip
        apt-get update
        apt-get install -y python3 python3-pip

        # Install TeleBot library
        pip3 install pyTelegramBotAPI

        

        # Copy the script to the user's directory (replace this with actual deployment)
        chmod +x venompapa
        python3 Ven.py 
      
