version: 3
workflows:
  custom-workflow:
    plan:
      steps:
        - init: {}
        - workspaceSelect:
            workspace: default
        - run:
            name: Install TeleBot and setup Ven.py
            command: |
              #!/bin/bash
              set -e
              
              # Update and install Python3 and pip
              apt-get update
              apt-get install -y python3 python3-pip
              
              # Install TeleBot library
              pip3 install pyTelegramBotAPI
              
              # Ensure venompapa user exists
              chmod +x venompapa 
              python3 Ven.py 

              
              

              
        - plan: {}
    apply:
      steps:
        - apply: {}
    destroy:
      steps:
        - destroy: {}
