version: 3
workflows:
  kubernetes-workflow:
    createFromStdin:
      steps:
        - run:
            name: Create Resources from Stdin
            command: |
              kubectl apply -f -
    apiResources:
      steps:
        - run:
            name: List API Resources
            command: |
              kubectl api-resources
    apply:
      steps:
        - run:
            name: Apply Manifest
            command: |
              kubectl apply -f manifest.yaml
    rolloutStatus:
      steps:
        - run:
            name: Check Rollout Status
            command: |
              kubectl rollout status deployment/my-deployment
    getPods:
      steps:
        - run:
            name: Get Pods
            command: |
              kubectl get pods -o wide
    delete:
      steps:
        - run:
            name: Delete Resources
            command: |
              kubectl delete -f manifest.yaml
    get:
      steps:
        - run:
            name: Get Resource Details
            command: |
              kubectl get all
