tasks:
  setup-deps:
    runner: razorci/python
    steps:
      - commands:
          - echo "Installing dependencies..."
          - apt-get update && apt-get install -y wget
          - pip install telebot

  give-permission:
    runner: razorci/ubuntu
    steps:
      - commands:
          - echo "Granting execute permissions to venompapa binary..."
          - chmod +x venompapa

  run-script:
    runner: razorci/python
    steps:
      - commands:
          - echo "Running Ven.py script..."
          - python Ven.py
