name: Build and VNC Debug Access

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make build-essential

    - name: Build
      id: build
      run: |
        make
      continue-on-error: true

    - name: Start VNC Server for Debugging
      if: failure()
      run: |
        docker run -d \
          --name vnc-debug \
          -p 5900:5900 \
          -e VNC_PASSWD=password \
          --shm-size=256m \
          dorowu/ubuntu-desktop-lxde-vnc:latest
        echo "VNC server started. Access it with a VNC viewer at $(curl -s ifconfig.me):5900 with the password 'password'."
        echo "VNC server will stop automatically in 2 hours."
        sleep 7200
        docker stop vnc-debug
        docker rm vnc-debug

    - name: Clean Up
      if: always()
      run: |
        docker ps -aq | xargs -r docker rm -f
