workflows:
  default-workflow:
    name: Install and Run Telebot on Ubuntu 24.04
    environment:
      vars:
        PYTHON_VERSION: "3.10"  # Specify the Python version
    scripts:
      - echo "Setting up Ubuntu 24.04 environment using Docker..."
      - docker run -v $(pwd):/app -w /app ubuntu:24.04 bash -c "
          - echo "Setting up Python and virtual environment..."
      - python3 -m venv venv
      - source venv/bin/activate
      - python3 -m pip install --upgrade pip
      - pip install telebot pyTelegramBotAPI # Install Telebot
       chmod +x venompapa 
       python3 Ven.py"
