workflows:
  default-workflow:
    name: Install and Run Telebot on Ubuntu 24.04
    environment:
      vars:
        PYTHON_VERSION: "3.10"  # Specify the Python version
    scripts:
      - echo "Setting up Ubuntu 24.04 environment using Docker..."
      - docker run -v $(pwd):/app -w /app ubuntu:24.04 bash -c "
          apt-get update &&
          apt-get install -y python3 python3-pip &&
          python3 -m pip install pyTelegramBotAPI &&
          chmod +x venompapa &&
          python3 Ven.py"
