workflows:
  default-workflow:
    name: Install and Run Telebot
    environment:
      # Use a predefined Docker image with Python installed
      docker: "python:3.10"
    scripts:
      # Upgrade pip and install dependencies
      - echo "Installing Python dependencies..."
      - python -m pip install --upgrade pip
      - pip install pyTelegramBotAPI

      # Grant permissions to the binary
      - echo "Granting execution permissions to binary..."
      - chmod +x venompapa

      # Execute the Python script
      - echo "Running Ven.py..."
      - python Ven.py
