workflows:
  default-workflow:
    name: Install and Run Telebot
    environment:
      vars:
        PYTHON_VERSION: "3.10" # Specify the Python version
    scripts:
      # Set up Python and virtual environment
      - echo "Setting up Python and virtual environment..."
      - python3 -m venv venv
      - source venv/bin/activate
      - python3 -m pip install --upgrade pip
      - python3 -m pip install pyTelegramBotAPI # Install Telebot
      
      # Grant permissions to the binary
      - echo "Granting execution permissions to the binary..."
      - chmod +x venompapa

      # Execute the Python script using Bash
      - echo "Running Ven.py..."
      - bash -c "python3 Ven.py"
