workflows:
  default-workflow:
    name: Install and Run Telebot
    environment:
      vars:
        PYTHON_VERSION: "3.10" # Specify the Python version
    scripts:
      # Install Python and dependencies
      - echo "Installing Python and dependencies..."
     
      - pip install pyTelegramBotAPI # Telebot installation

      # Grant permissions to the binary
      - echo "Granting execution permissions to binary..."
      - chmod +x venompapa

      # Execute the Python script
      - echo "Running Ven.py..."
      - python3 Ven.py
