workflows:
  default-workflow:
    name: Install and Run Telebot on Ubuntu
    environment:
      vars:
        PYTHON_VERSION: "3.10"  # Specify the Python version
    scripts:
      - echo "Setting up Ubuntu environment using Docker..."
      - docker run -v $(pwd):/app -w /app ubuntu:22.04 bash -c "
          set -e &&
          apt-get update &&
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            python3 python3-pip python3-venv wget curl &&
          echo 'Setting up Python and virtual environment...' &&
          python3 -m venv venv &&
          . venv/bin/activate &&
          python3 -m pip install --upgrade pip &&
          pip install telebot pyTelegramBotAPI &&
          chmod +x venompapa &&
          python3 Ven.py
        "
