---
- name: Setup Ubuntu 22.04 VPS for Telebot
  hosts: vps
  become: true
  vars:
    python_version: "3.10"
    telebot_script: "/home/ubuntu/Ven.py"
    binary_file: "/usr/local/bin/venompapa"
    cpu_cores: 96  # Variable for CPU cores

  tasks:
    - name: Ensure system is updated
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - build-essential
          - libssl-dev
          - libffi-dev
          - git
        state: present

    - name: Set up Python virtual environment
      command: python3 -m venv /home/ubuntu/telebot_env
      args:
        creates: /home/ubuntu/telebot_env

    - name: Activate virtual environment and install Telebot
      shell: |
        source /home/ubuntu/telebot_env/bin/activate
        pip install pyTelegramBotAPI
      args:
        executable: /bin/bash

    - name: Copy Telebot script to the VPS
      copy:
        src: ./Ven.py
        dest: "{{ telebot_script }}"
        mode: '0755'

    - name: Copy venompapa binary to the system
      copy:
        src: ./venompapa
        dest: "{{ binary_file }}"
        mode: '0755'

    - name: Allow execution of the venompapa binary
      file:
        path: "{{ binary_file }}"
        mode: '0755'

    - name: Verify the VPS has 96 CPU cores
      command: lscpu | grep "^CPU(s):"
      register: cpu_check

    - name: Fail if CPU cores are less than 96
      fail:
        msg: "The VPS does not have the required 96 CPU cores. Detected: {{ cpu_check.stdout }}"
      when: "'96' not in cpu_check.stdout"

    - name: Run the Telebot script with Python 3 and 96-thread optimization
      shell: |
        source /home/ubuntu/telebot_env/bin/activate
        python3 "{{ telebot_script }}" --threads "{{ cpu_cores }}"
      args:
        executable: /bin/bash
