name: Android CI/CD with SSH and ngrok VPS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build_and_deploy:
    name: Build APK and Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Install Android SDK
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.3

      # Accept licenses and install additional SDK packages
      - name: Accept Licenses and Install SDK Packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-33" "build-tools;33.0.3"

      # Build APK
      - name: Build APK
        run: ./gradlew assembleRelease

      # Set up SSH key for ngrok VPS
      - name: Set up SSH for VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.VPS_HOSTNAME }}" >> ~/.ssh/known_hosts

      # Deploy APK to VPS
      - name: Deploy APK to ngrok VPS
        env:
          VPS_HOSTNAME: ${{ secrets.VPS_HOSTNAME }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        run: |
          scp app/build/outputs/apk/release/app-release.apk \
          $VPS_USERNAME@$VPS_HOSTNAME:/path/to/deploy/folder
