name: Setup VPS with SSH for User 'venom'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  setup_vps:
    name: Set up SSH for VPS
    runs-on: ubuntu-24.04
    steps:
      # Configure SSH with the provided private key
      - name: Set up SSH for User 'venom'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.RSA_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.VPS_HOSTNAME }}" >> ~/.ssh/known_hosts

      # Test SSH Connection for User 'venom'
      - name: Test SSH connection for user 'venom'
        env:
          VPS_HOSTNAME: ${{ secrets.VPS_HOSTNAME }}
        run: |
          ssh -vvv -o StrictHostKeyChecking=no venom@${{ secrets.VPS_HOSTNAME }} "echo 'Connection successful for user venom!'"
