name: Setup VPS with SSH

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  setup_vps:
    name: Set up SSH for VPS
    runs-on: ubuntu-latest
    steps:
      # Debugging: Check Runner Environment
      - name: Debug Environment
        run: |
          echo "Runner User: $(whoami)"
          echo "Runner Home Directory: $HOME"

      # Configure SSH
      - name: Set up SSH for VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.VPS_HOSTNAME }}" >> ~/.ssh/known_hosts

      # Test SSH Connection
      - name: Test SSH connection
        env:
          VPS_HOSTNAME: ${{ secrets.VPS_HOSTNAME }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        run: |
          ssh -vvv -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_HOSTNAME "echo 'Connection successful!'"
